site_name: The Thief Game Design Documentation
site_author: 'hzy'
site_description: 'The Thief Game Design Documentation'

#edit_uri: 'Design/docs/'

nav:
- 主要设计: index.md
- 用户登入:
  - 游戏入口: 游戏入口/游戏入口系统策划案.md
- 关卡:
  - 关卡模块: 关卡模块/关卡模块系统策划案.md
  - 关卡规划: 关卡模块/关卡策划.md
  - 场景交互: 关卡模块/场景交互.md
  - 资源: 资源补给模块/补给.md
- 声音:
  - 声效模块: 声效模块/声效模块系统策划案.md
- 界面:
  - 匹配界面: 匹配模块/匹配模块系统策划.md
  - 游戏界面: HUD模块/游戏界面.md
  - 地图界面: HUD模块/地图.md
  - 背包界面: HUD模块/背包.md
  - 设置界面: HUD模块/设置.md
  - 结算界面: HUD模块/结算.md
  - 转场界面: HUD模块/转场.md
- 游戏逻辑模块: 
  - 时间: 对局流程控制/游戏流程控制（时间）.md
  - 空间: 对局流程控制/游戏流程控制（空间）.md
- 战斗模块 :
  - 武器: 武器模块/武器.md
  - 角色控制: 角色控制模块/角色控制模块.md
  - 道具: 道具模块/道具模块.md
  - 场景交互: 关卡模块/场景交互.md
- 阵营模块:
  - 阵营: 阵营模块/阵营.md
  - NPC模块: NPC/NPC.md
- 相机: 相机模块/相机模块.md

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  #- pymdownx.caret  # 下划线上标
  #- pymdownx.tilde  # 删除线下标
  #- pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  #- pymdownx.details  # 提示块可折叠
  #- pymdownx.inlinehilite  # 行内代码高亮
  #- pymdownx.mark  # 文本高亮
  #- pymdownx.smartsymbols  # 符号转换
  #- pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  #- pymdownx.betterem:  # 对加粗和斜体更好的检测
  #    smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  #- pymdownx.tasklist:  # 复选框checklist
  #    custom_checkbox: true

theme: readthedocs
